In [152]:
from collections import defaultdict
import pandas as pd
import numpy as np
import sklearn
import re

In [177]:
recipe_data = pd.read_csv('nyu_recipe_data.csv')
tagging_structure = pd.read_csv('Tagging_structure.csv')

Filter out rows with no tags

In [178]:
recipe_data_with_tags = recipe_data.dropna(subset=['recipe_tags'])
#recipe_data_wo_tags = recipe_data[recipe_data['recipe_tags'].isna()]
#print('There is {} recipes without tags in {}'.format(len(recipe_data_wo_tags), len(recipe_data)))

Prepare to clean out data

In [179]:
def clean_html(raw_html):
    try:
        cleanr1 = re.compile('<.*?>')
        repeatr1 = re.sub(cleanr1, '', raw_html)
        cleanr2 = re.compile(r'&nbsp;')
        repeatr2 = re.sub(cleanr2, '', repeatr1)
        cleanr3 = re.compile('&#x27;')
        repeatr3 = re.sub(cleanr3, "'", repeatr2)
        repeatr4 = repeatr3.replace('<b>', '').replace('</b>', '').replace('[', '').replace(']', '').replace('#','')
        return repeatr4
    except:
        #print('NAN: ', raw_html)
        return raw_html
    
def auto_clean(init_clean):
    try:
        return clean_html_dirt(init_clean)[0:6]+clean_html_dirt(init_clean).split(clean_html_dirt(init_clean)[0:6])[1]
    except:
        #print('---------')
        return init_clean

In [180]:
text_columns = ['cooking_tips', 'story', 'ingredients_display']

for col_name in text_columns:
    recipe_data_with_tags[col_name] = recipe_data_with_tags.apply(lambda row: clean_html(row[col_name]), axis=1)
    x = recipe_data_with_tags[recipe_data_with_tags[col_name].isnull()==True].index.values   
    print('<', col_name, '> contains nan in row:\n', x)

NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
NAN:  nan
< cooking_tips > contains nan in row:
 [   6    7    8    9   10   11   12   13   14   15   16   17 

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [181]:
step_columns = ['step_one', 'step_two', 'step_three', 'step_four', 'step_five','step_six']
for col_name in step_columns:
    recipe_data_with_tags[col_name] = recipe_data_with_tags.apply(lambda row: auto_clean(row[col_name]), axis=1)
    x = recipe_data_with_tags[recipe_data_with_tags[col_name].isnull()==True].index.values   
    print('<', col_name, '> contains nan in row:\n', x)

NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_one > contains nan in row:
 [1214 1996 2315 2441]


/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_two > contains nan in row:
 [1365 1927 2285 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_three > contains nan in row:
 [1972 2015 2387 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_four > contains nan in row:
 [1333 1745 2015 2234 2309 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_five > contains nan in row:
 [ 765 1481 1733 1899 2276 2375 2545 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
--------

In [182]:
# two tag sets
tag_set_structure = set(tagging_structure['Tag Name'].values)
tags_set = set()
for index, item in recipe_data['recipe_tags'].iteritems():
    try:
        item = item.split(', ')
        tags_set.update(item)
    except:
        pass

In [183]:
# build dict from class2 to class1
Tags_structure = pd.read_csv('Tags_structure_self.csv', index_col=0)
Class2_class1_dict = defaultdict(set)
for index, row in Tags_structure.iterrows():
    Class2_class1_dict[row['Class2']].add(row['Class1'])

In [184]:
cuisine_tags = Class2_class1_dict['cuisine']
prefix_cuisine = 'tag_cuisine_'
for item in cuisine_tags:
    recipe_data_with_tags[prefix_cuisine+item] = 0

for index, item in recipe_data_with_tags['recipe_tags'].iteritems():
    tags = item
    tags = tags.split(', ')
    for tag in tags:
        if tag in cuisine_tags:
            recipe_data_with_tags.at[index, prefix_cuisine+tag] = 1

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [185]:
recipe_data_with_tags.to_csv('cleaned_recipe_data.csv')

### Analysis of tags

In [18]:
# frequence of each tag for cuisine 
for item in cuisine_tags: 
    print(item, recipe_data_with_tags[prefix_cuisine+item].sum())

indian 59
nordic 1
european 31
asian 457
mexican 34
latin-american 238
french 194
italian 585
african 10
mediterranean 192
american 686
middle-eastern 116


In [19]:
#number of tags for each recipe
cuisine_tag_num = pd.Series(0, index=recipe_data_with_tags.index, name='cuisine_tag_num')
for item in cuisine_tags: 
    cuisine_tag_num = cuisine_tag_num + recipe_data_with_tags[prefix_cuisine+item]

cuisine_tag_num.groupby(cuisine_tag_num).count()

0      47
1    2323
2     134
3       4
dtype: int64

### Analysis of features

In [20]:
recipe_data_with_tags.head(10)

external_id                                              title  \
0  a41b3718c9                                       Seared Steak   
1  2cf0cfc9c1                                        Orange Beef   
2  aa948d577f                               Garlic-Soy Pork Chop   
3  e96886e2e2                              Crispy Chickpea Bowls   
4  dfe70b7ce7                          Green Chile Chicken Tacos   
5  cdabd5c0ee                            Fontina-Stuffed Chicken   
6  1b131c638a   Caramelized Parsnip and Butternut Squash Risotto   
7  44628149f0                              Sticky asian Calamari   
8  28b00c76a3  French-Inspired Salmon Tacos with Pickly Cucum...   
9  ac26c8473d                             Herb roasted pork chop   

                                            subtitle  carbs   fat  protein  \
0  with Roasted Green Beans and Smoky Paprika Butter   29.0  22.0     37.0   
1                 with Bell Pepper and Scallion Rice   89.0  22.0     37.0   
2                  with Bok Choy and Water Chestnuts   71.0  23.0     43.0   
3                            with Harissa-Baked Feta   80.0  47.0     32.0   
4                           with Mexican Street Corn   62.0  37.0     39.0   
5  with Roasted Potatoes, Brussels Sprouts, and Peas   59.0  33.0     60.0   
6                   with Whipped Parmesan Mascarpone    NaN   NaN      NaN   
7                             with long life noodles    NaN   NaN      NaN   
8                      and Creamy Dill-Mustard Sauce    NaN   NaN      NaN   
9                      with creamy mushroom farrotto    NaN   NaN      NaN   

   chef_id calories                                       cooking_tips  \
0      118      440  Be sure to read through the entire recipe befo...   
1      113      700  Be sure to read through the entire recipe befo...   
2        1      660  Be sure to read through the entire recipe befo...   
3      119      840  Be sure to read through the entire recipe befo...   
4       75      750  Be sure to read through the entire recipe befo...   
5        1      750  Be sure to read through the entire recipe befo...   
6      154      NaN                                                NaN   
7      119      NaN                                                NaN   
8      154      NaN                                                NaN   
9      119      NaN                                                NaN   

                                               story  \
0  We love infusing butter with other ingredients...   
1  When it comes to Chinese takeout, orange beef ...   
2  This week, Chef Elana strove to take the elega...   
3  When we asked Chef Giuseppe to revamp our ever...   
4  We love tacos with a little heat! The proof: T...   
5  Stuffing meat before cooking is a popular tech...   
6                                                NaN   
7                                                NaN   
8                                                NaN   
9                                                NaN   

              ...             tag_cuisine_european tag_cuisine_asian  \
0             ...                                1                 0   
1             ...                                0                 1   
2             ...                                0                 1   
3             ...                                0                 0   
4             ...                                0                 0   
5             ...                                0                 0   
6             ...                                0                 0   
7             ...                                0                 1   
8             ...                                0                 0   
9             ...                                0                 0   

  tag_cuisine_mexican tag_cuisine_latin-american tag_cuisine_french  \
0                   0                          0                  0   
1                   0      

In [21]:
recipe_data_with_tags.isna().sum()

AttributeError: 'DataFrame' object has no attribute 'isna'

In [22]:
recipe_data_with_tags[recipe_data_with_tags["carbs"].isna()].isna().sum()

AttributeError: 'Series' object has no attribute 'isna'

### only 1 row has subtitle as null and exists others value 

In [ ]:
recipe_data_with_tags[~recipe_data_with_tags["carbs"].isna()&(recipe_data_with_tags["subtitle"].isna())]

## Get Most frequent words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)
X=vectorizer.fit_transform(recipe_data_with_tags["title"])
word_count=np.sum (X.toarray(), axis=0)
index_sort=np.argsort(-word_count)
[vectorizer.get_feature_names()[x] for x in index_sort]

In [ ]:
recipe_data_with_tags[["carbs", "fat", "protein"]].describe()

### Analysis of ingredients data

In [ ]:
ingredients = recipe_data_with_tags['ingredients_display']
ing_cnt = []
ing_dic = {}
for i in ingredients:
    ing_cnt.append(i.count(','))
    ing_lst = i.split(",")
    for m in ing_lst:
        if m not in ing_dic.keys():
            ing_dic[m] = 1
        else:
            ing_dic[m] = ing_dic[m] + 1
    

In [ ]:
df = pd.DataFrame(ing_cnt, columns = ['ing_cnt'])
df['ing_cnt'].hist()

In [ ]:
df.describe()

In [ ]:
ing_dic.keys()

In [ ]:
len(ing_dic)

In [ ]:
cnt_lst = list(ing_dic.values())
cnt_lst.sort()
total = sum(cnt_lst)
top50 = sum(cnt_lst[-50:])

top50/total

#### Recipes contain missing values:

In [ ]:
for col_name in step_columns:
    recipe_data_with_tags[col_name] = recipe_data_with_tags.apply(lambda row: auto_clean(row[col_name]), axis=1)
    x = recipe_data_with_tags[recipe_data_with_tags[col_name].isnull()==True].index.values.tolist()
    missings = []
    missings.extend(x)
    #empty.append(x)  
print('****************')
print('Recipes contain one or more missing steps:')
print(set(missings))
print('****************')

#### Calculate the average/max/min length of each instruction step: 

In [ ]:
for col_name in step_columns:
    length = []
    n = 0
    for i in range(0,recipe_data_with_tags.shape[0]):
        try:
            length.append(len(recipe_data_with_tags[col_name][i].split()))
            n += 1
        except:
            pass
    print(col_name,':')
    print('max length: ', max(length))
    print('min length: ', min(length))
    print('average length: ', np.sum(length)/n)
    print('====================')