In [1]:
import pandas as pd
import numpy as np
import re

In [111]:
dt = pd.read_csv('nyu_recipe_data.csv')

In [128]:
def clean_html_dirt(raw_html):
    try:
        cleanr1 = re.compile('<.*?>')
        repeatr1 = re.sub(cleanr1, '', raw_html)
        cleanr2 = re.compile(r'&nbsp;')
        repeatr2 = re.sub(cleanr2, '', repeatr1)
        cleanr3 = re.compile('&#x27;')
        repeatr3 = re.sub(cleanr3, "'", repeatr2)
        repeatr4 = repeatr3.replace('<b>', '').replace('</b>', '')
        return repeatr4
    except:
        print('NAN: ', raw_html)
        return raw_html
def deep_clean(init_clean):
    try:
        return clean_html_dirt(init_clean)[0:5]+clean_html_dirt(init_clean).split(clean_html_dirt(init_clean)[0:5])[1]
    except:
        print('---------')
        return init_clean

In [124]:
col = ['step_one', 'step_two', 'step_three', 'step_four', 'step_five','step_six']

#### Clean and missing values in each instruction steps:

In [129]:
for col_name in col:
    dt[col_name] = dt.apply(lambda row: deep_clean(row[col_name]), axis=1)
    x = dt[dt[col_name].isnull()==True].index.values   
    print('<', col_name, '> contains nan in row:\n', x)

NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_one > contains nan in row:
 [1214 1996 2315 2441]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_two > contains nan in row:
 [1365 1378 1927 2285 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_three > contains nan in row:
 [1378 1482 1972 2015 2387 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_four > contains nan in row:
 [1333 1378 1477 1482 1745 2015 2234 2309 2559]
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
NAN:  nan
---------
< step_five > contains nan in

#### Cleaned sample

In [116]:
import random 
dt.step_five[random.randint(1,dt.shape[0]+1)]

'Season tilapia all over with .25 teaspoon kosher salt and pepper as desired. Add to pot with curry, nestling in. Increase heat to medium high and cook until tilapia is opaque, about 5 minutes. Remove pot from heat. Using a spoon, break tilapia into smaller pieces. Taste and add more salt and pepper as needed.'

In [130]:
for i in dt['step_four'].values:
    try:
        if "<b>" in i:
            print(i)
    except:
        pass

#### Recipes contain missing values:

In [7]:
for col_name in col:
    dt[col_name] = dt.apply(lambda row: deep_clean(row[col_name]), axis=1)
    x = dt[dt[col_name].isnull()==True].index.values.tolist()
    missings = []
    missings.extend(x)
    #empty.append(x)  
print('****************')
print('Recipes contain one or more missing steps:')
print(set(missings))
print('****************')
# print('Recipes ONLY contain step-one:', list(set(empty[1]) & set(empty[2]) &set(empty[3]) & set(empty[4])&set(empty[5])))  
# print('Recipes ONLY contain step-one & step-two:', list(set(empty[2]) &set(empty[3]) & set(empty[4])&set(empty[5]))[0])  
# print('Recipes ONLY contain step-one & two & three:', list(set(empty[3]) & set(empty[4])&set(empty[5]))[1])  

****************
Recipes contain one or more missing steps:
{1572, 2346, 1836, 1967, 1584, 1714, 2485, 1468, 1859, 1477, 1482, 2123, 2380, 2125, 1870, 1998, 2512, 2001, 1234, 2514, 2520, 2139, 1244, 2141, 2142, 2143, 2526, 2273, 1378, 1764, 2536, 2545, 2162, 2036, 1910, 2554, 893, 2559}
****************


#### Calculate the average/max/min length of each instruction step: 

In [14]:
for col_name in col:
    length = []
    n = 0
    for i in range(0,dt.shape[0]):
        try:
            length.append(len(dt[col_name][i].split()))
            n += 1
        except:
            pass
    print(col_name,':')
    print('max length: ', max(length))
    print('min length: ', min(length))
    print('average length: ', np.sum(length)/n)
    print('====================')

step_one :
max length:  94
min length:  4
average length:  52.36942924159499
step_two :
max length:  86
min length:  13
average length:  51.197888150175984
step_three :
max length:  87
min length:  9
average length:  52.41158059467919
step_four :
max length:  90
min length:  5
average length:  51.66039952996475
step_five :
max length:  100
min length:  8
average length:  48.95060760486084
step_six :
max length:  91
min length:  5
average length:  31.89659270998415
